version: "3"

services:
  server:
    image: docker.io/gitea/gitea:1.22.6
    container_name: githot
    environment:
      - USER=git
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=githot
      - GITEA__database__USER=githot
      - GITEA__database__PASSWD=git@1234
    restart: always
    networks:
      - githot
    volumes:
      - ./data:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "127.0.0.1:2222:22"
    depends_on:
      - db

   db:
     image: docker.io/library/postgres:14
     restart: always
     environment:
       - POSTGRES_USER=githot
       - POSTGRES_PASSWORD=git@1234
       - POSTGRES_DB=githot
     networks:
       - gitea
     volumes:
       - ./postgres:/var/lib/postgresql/data

networks:
  githot:
    external: 

